// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mbzmjevvegalxehuscam.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1iem1qZXZ2ZWdhbHhlaHVzY2FtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMzExOTcsImV4cCI6MjA2NzYwNzE5N30.zjHW6bEyvSm-xKgC5dWs1EcVlMFF0mbhvjTCTDL2kxM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});